catalog:
  '@biomejs/biome': 2.4.11
  '@effect/experimental': ^0.60.0
  '@effect/language-service': ^0.73.1
  '@effect/opentelemetry': ~4.0.0-beta.52
  '@effect/platform': ^0.96.0
  '@effect/platform-bun': 4.0.0-beta.55
  '@effect/sql-pg': ~4.0.0-beta.52
  '@effect/sql-sqlite-bun': 4.0.0-beta.55
  '@mastra/core': ^1.23.0
  '@mastra/evals': ^1.2.0
  '@mastra/hono': ^1.4.1
  '@mastra/libsql': ^1.8.0
  '@mastra/loggers': ^1.1.0
  '@mastra/mcp': ^1.4.1
  '@mastra/memory': ^1.13.1
  '@mastra/observability': ^1.7.2
  '@mastra/rag': ^2.1.3
  '@mastra/schema-compat': 1.2.7
  '@mastra/server': ^1.23.0
  '@types/bun': ^1.2.0
  '@yuyi919/shared-proto': ^0.1.23
  '@yuyi919/tslibs-effect': ^0.4.2
  effect: ~4.0.0-beta.52
  mastra: ^1.4.0
  react: ^19.1.0
  react-dom: ^19.1.0
  zod: ^4.3.6
